language: c++
sudo: required
dist: trusty
cache: ccache

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y codeblocks

script:
  - codeblocks --target=HelloWorld_lin --rebuild ./POKITTO_SIM/Pokitto_sim.cbp

